version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=8004
      - NODE_ENV=production
      - FRONTEND_URL=https://p.millio.space
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    ports:
      - "8004:8004"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=http://pi.millio.space/api
    ports:
      - "8005:80"
    depends_on:
      - backend
    restart: unless-stopped
