version: '3.8'

services:
  # Main FastAPI application
  app:
    build: .
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=patient_user
      - POSTGRES_PASSWORD=patient_password
      - POSTGRES_DB=patient_visits
      - DATABASE_URL=postgresql+asyncpg://patient_user:patient_password@db:5432/patient_visits
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=patient_user
      - POSTGRES_PASSWORD=patient_password
      - POSTGRES_DB=patient_visits
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U patient_user -d patient_visits"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: